"""Slice pipeline tests.

The metadata parser is tested against a fixture that reproduces PrusaSlicer's real
layout — in particular the fact that the interesting comments sit *before* the
several-hundred-line config block, not at the end of the file. A parser that reads
the tail passes a naive test and fails on real output.
"""

from __future__ import annotations

import shutil

import pytest

from vtp.config import slicer_profile
from vtp.slicer import SliceResult, SlicerError, _parse_duration, slice_stl

pytestmark = pytest.mark.filterwarnings("ignore::DeprecationWarning")

REAL_SLICER = shutil.which("prusa-slicer") is not None

#: Trimmed from real 2.9.4 output for box_with_lid_body.stl: three layer markers,
#: the metadata block, then the config block that follows it in a real file.
FIXTURE_GCODE = """\
; generated by PrusaSlicer 2.9.4+UNKNOWN
M190 S60
G28 ; home all axis
G29 ; auto bed levelling
;LAYER_CHANGE
;Z:0.2
G1 X10 Y10 E1.0
;LAYER_CHANGE
;Z:0.4
G1 X20 Y20 E2.0
;LAYER_CHANGE
;Z:0.6
G1 X30 Y30 E3.0
M107 ; turn off fan
M84 X Y E ; disable motors
; filament used [mm] = 1426.18
; filament used [cm3] = 3.43
; filament used [g] = 4.25
; filament cost = 0.09
; total filament used [g] = 4.25
; estimated printing time (normal mode) = 30m 44s
; estimated first layer printing time (normal mode) = 2m 39s

; prusaslicer_config = begin
; layer_height = 0.2
; filament used [g] = 999.99
; z_offset = 0
; prusaslicer_config = end
"""


def write_gcode(tmp_path, text=FIXTURE_GCODE, name="part.gcode"):
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


def fake_slice(tmp_path, monkeypatch, gcode_text=FIXTURE_GCODE, returncode=0):
    """Stub PrusaSlicer: write the fixture where --output says, then exit."""
    import subprocess

    stl = tmp_path / "part.stl"
    stl.write_bytes(b"solid x\nendsolid x\n")

    def run(command, **kwargs):
        target = command[command.index("--output") + 1]
        if returncode == 0:
            with open(target, "w", encoding="utf-8") as fh:
                fh.write(gcode_text)
        return subprocess.CompletedProcess(command, returncode, "progress 90%", "")

    monkeypatch.setattr(subprocess, "run", run)
    monkeypatch.setattr("vtp.slicer.shutil.which", lambda _: "/usr/bin/prusa-slicer")
    return stl


# --------------------------------------------------------------------------- #
# Duration parsing
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "text,seconds",
    [
        ("30m 44s", 1844),
        ("44s", 44),
        ("1h 2m 3s", 3723),
        ("2d 4h 30m 10s", 189010),
        ("30m44s", 1844),  # no space — older output
    ],
)
def test_duration_parses(text, seconds):
    assert _parse_duration(text) == seconds


def test_duration_rejects_nonsense_naming_the_value():
    with pytest.raises(SlicerError, match="soon"):
        _parse_duration("soon")


# --------------------------------------------------------------------------- #
# Metadata parsing
# --------------------------------------------------------------------------- #


def test_parses_the_real_footer_layout(tmp_path, monkeypatch):
    stl = fake_slice(tmp_path, monkeypatch)
    result = slice_stl(stl, output=tmp_path / "part.gcode")

    assert isinstance(result, SliceResult)
    assert result.filament_g == 4.25
    assert result.filament_mm == 1426.18
    assert result.filament_cm3 == 3.43
    assert result.print_time_text == "30m 44s"
    assert result.print_time_seconds == 1844
    assert result.layer_count == 3


def test_first_filament_value_wins_over_the_config_block_echo():
    """`; filament used [g]` appears again inside prusaslicer_config with a
    different value. Reading the last match would report 999.99 g."""
    from vtp.slicer import _parse_gcode
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as d:
        path = Path(d) / "p.gcode"
        path.write_text(FIXTURE_GCODE, encoding="utf-8")
        assert _parse_gcode(path)["filament_g"] == 4.25


def test_layer_count_comes_from_markers(tmp_path, monkeypatch):
    text = FIXTURE_GCODE.replace(";LAYER_CHANGE", ";LAYER_CHANGE", 1)
    extra = text + ";LAYER_CHANGE\n;Z:0.8\n"
    stl = fake_slice(tmp_path, monkeypatch, gcode_text=extra)
    assert slice_stl(stl, output=tmp_path / "p.gcode").layer_count == 4


def test_gcode_without_metadata_is_rejected(tmp_path, monkeypatch):
    stl = fake_slice(tmp_path, monkeypatch, gcode_text=";LAYER_CHANGE\nG1 X1\n")
    with pytest.raises(SlicerError, match="missing expected PrusaSlicer metadata"):
        slice_stl(stl, output=tmp_path / "p.gcode")


def test_gcode_with_no_layers_is_rejected(tmp_path, monkeypatch):
    text = FIXTURE_GCODE.replace(";LAYER_CHANGE\n", "")
    stl = fake_slice(tmp_path, monkeypatch, gcode_text=text)
    with pytest.raises(SlicerError, match="no layers"):
        slice_stl(stl, output=tmp_path / "p.gcode")


# --------------------------------------------------------------------------- #
# Input guards and failure reporting
# --------------------------------------------------------------------------- #


def test_missing_stl_is_named(tmp_path):
    with pytest.raises(SlicerError, match="no such STL"):
        slice_stl(tmp_path / "absent.stl")


def test_non_stl_input_is_rejected(tmp_path):
    other = tmp_path / "part.gcode"
    other.write_text("hi", encoding="utf-8")
    with pytest.raises(SlicerError, match="not an STL"):
        slice_stl(other)


def test_empty_stl_is_rejected(tmp_path):
    empty = tmp_path / "part.stl"
    empty.touch()
    with pytest.raises(SlicerError, match="empty"):
        slice_stl(empty)


def test_missing_profile_warns_against_generating_one(tmp_path, monkeypatch):
    stl = fake_slice(tmp_path, monkeypatch)
    with pytest.raises(SlicerError, match="do not generate a replacement"):
        slice_stl(stl, profile=tmp_path / "nope.ini")


def test_slicer_failure_includes_its_stderr(tmp_path, monkeypatch):
    import subprocess

    stl = tmp_path / "part.stl"
    stl.write_bytes(b"solid x\nendsolid x\n")
    monkeypatch.setattr("vtp.slicer.shutil.which", lambda _: "/usr/bin/prusa-slicer")
    monkeypatch.setattr(
        subprocess,
        "run",
        lambda command, **kw: subprocess.CompletedProcess(
            command, 1, "", "object outside the print area"
        ),
    )
    with pytest.raises(SlicerError, match="object outside the print area"):
        slice_stl(stl, output=tmp_path / "p.gcode")


def test_zero_exit_without_output_is_still_a_failure(tmp_path, monkeypatch):
    import subprocess

    stl = tmp_path / "part.stl"
    stl.write_bytes(b"solid x\nendsolid x\n")
    monkeypatch.setattr("vtp.slicer.shutil.which", lambda _: "/usr/bin/prusa-slicer")
    monkeypatch.setattr(
        subprocess,
        "run",
        lambda command, **kw: subprocess.CompletedProcess(command, 0, "done", ""),
    )
    with pytest.raises(SlicerError, match="wrote no G-code"):
        slice_stl(stl, output=tmp_path / "p.gcode")


def test_captures_child_output_rather_than_inheriting_it(tmp_path, monkeypatch):
    """PrusaSlicer prints progress to stdout; under stdio transport that stream is
    JSON-RPC. Inheriting it would corrupt the protocol."""
    import subprocess

    seen = {}
    stl = tmp_path / "part.stl"
    stl.write_bytes(b"solid x\nendsolid x\n")
    monkeypatch.setattr("vtp.slicer.shutil.which", lambda _: "/usr/bin/prusa-slicer")

    def run(command, **kwargs):
        seen.update(kwargs)
        target = command[command.index("--output") + 1]
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(FIXTURE_GCODE)
        return subprocess.CompletedProcess(command, 0, "", "")

    monkeypatch.setattr(subprocess, "run", run)
    slice_stl(stl, output=tmp_path / "p.gcode")
    assert seen["capture_output"] is True


def test_summary_reads_back_the_numbers(tmp_path, monkeypatch):
    stl = fake_slice(tmp_path, monkeypatch)
    summary = slice_stl(stl, output=tmp_path / "p.gcode").summary()
    assert "3 layers" in summary
    assert "4.25 g" in summary
    assert "30m 44s" in summary


# --------------------------------------------------------------------------- #
# Acceptance — the real slicer, the real profile
# --------------------------------------------------------------------------- #


@pytest.mark.skipif(not REAL_SLICER, reason="prusa-slicer not installed")
def test_acceptance_slices_the_verified_part(tmp_path):
    """Phase 2 acceptance: the Phase 1 STL slices, and its metadata matches the
    physically verified print — 55 layers, 4.25 g, 30m 44s."""
    from vtp.cad import design

    designed = design(
        "box_with_lid",
        {
            "outer_l": 30.6,
            "outer_w": 27.7,
            "outer_h": 11.0,
            "ports": [
                {"side": "left", "width": 9.0, "height": 5.5},
                {"side": "right", "width": 9.0, "height": 5.5},
            ],
        },
        output_dir=tmp_path,
        render=False,
    )

    result = slice_stl(designed.stl_paths["body"], output=tmp_path / "body.gcode")
    assert result.profile == slicer_profile()
    assert result.layer_count == 55
    assert result.filament_g == pytest.approx(4.25, abs=0.1)
    assert result.print_time_seconds == pytest.approx(1844, abs=120)
    assert result.gcode_path.stat().st_size > 0


# --------------------------------------------------------------------------- #
# Bed pre-flight
# --------------------------------------------------------------------------- #


def test_oversized_part_is_refused_before_the_slicer_runs(tmp_path, monkeypatch):
    """PrusaSlicer rejects it too, but names neither the axis nor the overshoot."""
    import subprocess

    from vtp.cad import design

    designed = design(
        "box_with_lid",
        {"outer_l": 400.0, "outer_w": 30.0, "outer_h": 15.0},
        output_dir=tmp_path,
        render=False,
    )

    def explode(*args, **kwargs):
        raise AssertionError("the slicer must not be invoked for an oversized part")

    monkeypatch.setattr(subprocess, "run", explode)

    with pytest.raises(SlicerError, match=r"X is 400mm .* limit is 220mm"):
        slice_stl(designed.stl_paths["body"], output=tmp_path / "big.gcode")


def test_an_unreadable_mesh_defers_to_the_slicer(tmp_path, monkeypatch):
    """Whether a file is parseable is PrusaSlicer's call, in its own words."""
    stl = fake_slice(tmp_path, monkeypatch)
    monkeypatch.setattr(
        "trimesh.load_mesh", lambda *a, **k: (_ for _ in ()).throw(ValueError("nope"))
    )
    # Slices normally: the bed check declines to have an opinion.
    assert slice_stl(stl, output=tmp_path / "p.gcode").layer_count == 3


# --------------------------------------------------------------------------- #
# Stored bed mesh
#
# The swap is one line of the exported G-code, and every uncertain case must leave
# that line alone: M420 S1 against a mesh the printer does not have does not fail,
# it prints on a flat plane. "Slower and correct" is the only safe default.
# --------------------------------------------------------------------------- #


def store_mesh(isolated_mesh_state, age_days=0.0):
    """Claim a mesh was stored `age_days` ago, as calibrate_bed would have."""
    import json
    from datetime import UTC, datetime, timedelta

    when = datetime.now(UTC) - timedelta(days=age_days)
    isolated_mesh_state.write_text(
        json.dumps({"stored_at": when.isoformat(timespec="seconds"), "printer": "x"}),
        encoding="utf-8",
    )


def test_without_a_stored_mesh_the_probe_survives(tmp_path, monkeypatch):
    """The default path, and it must be byte-for-byte what the profile produced."""
    stl = fake_slice(tmp_path, monkeypatch)
    result = slice_stl(stl, output=tmp_path / "out.gcode")

    assert result.levelling == "probe"
    assert "no bed mesh has been stored" in result.levelling_detail
    assert result.gcode_path.read_text() == FIXTURE_GCODE


def test_a_stored_mesh_replaces_exactly_the_probe_line(
    tmp_path, monkeypatch, isolated_mesh_state
):
    store_mesh(isolated_mesh_state)
    stl = fake_slice(tmp_path, monkeypatch)
    result = slice_stl(stl, output=tmp_path / "out.gcode")

    assert result.levelling == "stored"
    before = FIXTURE_GCODE.splitlines()
    after = result.gcode_path.read_text().splitlines()

    assert len(before) == len(after)
    differing = [i for i, (a, b) in enumerate(zip(before, after)) if a != b]
    assert len(differing) == 1, "exactly one line may change"
    assert after[differing[0]].startswith("M420 S1")
    # No executable probe left. Checked per line, because the replacement comment
    # mentions G29 by name and a substring search would find that.
    assert not [line for line in after if line.strip().startswith("G29")]
    # Homing is not levelling and must survive.
    assert "G28 ; home all axis" in after
    # And nothing non-ASCII went into a file bound for a serial link.
    result.gcode_path.read_bytes().decode("ascii")


def test_a_stale_mesh_falls_back_to_probing(
    tmp_path, monkeypatch, isolated_mesh_state
):
    """Nothing can read a mesh back out of the printer, so age is the only signal."""
    store_mesh(isolated_mesh_state, age_days=90)
    stl = fake_slice(tmp_path, monkeypatch)
    result = slice_stl(stl, output=tmp_path / "out.gcode")

    assert result.levelling == "probe"
    assert "90" in result.levelling_detail
    assert result.gcode_path.read_text() == FIXTURE_GCODE


def test_an_unreadable_state_file_falls_back_to_probing(
    tmp_path, monkeypatch, isolated_mesh_state
):
    isolated_mesh_state.write_text("{not json", encoding="utf-8")
    stl = fake_slice(tmp_path, monkeypatch)
    result = slice_stl(stl, output=tmp_path / "out.gcode")

    assert result.levelling == "probe"
    assert result.gcode_path.read_text() == FIXTURE_GCODE


@pytest.mark.parametrize("count", [0, 2])
def test_a_missing_or_doubled_anchor_is_left_alone(
    tmp_path, monkeypatch, isolated_mesh_state, count
):
    """If the profile changed underneath us, guessing which line was meant is worse."""
    store_mesh(isolated_mesh_state)
    text = FIXTURE_GCODE.replace(
        "G29 ; auto bed levelling\n", "G29 ; auto bed levelling\n" * count
    )
    stl = fake_slice(tmp_path, monkeypatch, gcode_text=text)
    result = slice_stl(stl, output=tmp_path / "out.gcode")

    assert result.levelling == "probe"
    assert f"found {count}" in result.levelling_detail
    assert result.gcode_path.read_text() == text


def test_the_rewrite_leaves_no_temp_file_behind(
    tmp_path, monkeypatch, isolated_mesh_state
):
    """A half-written G-code must never be something a human can upload."""
    store_mesh(isolated_mesh_state)
    stl = fake_slice(tmp_path, monkeypatch)
    slice_stl(stl, output=tmp_path / "out.gcode")

    assert list(tmp_path.glob("*.tmp")) == []


def test_the_swap_does_not_disturb_the_metadata(
    tmp_path, monkeypatch, isolated_mesh_state
):
    """Gate 2's numbers describe the file that gets uploaded, swap or no swap."""
    stl = fake_slice(tmp_path, monkeypatch)
    probed = slice_stl(stl, output=tmp_path / "a.gcode")

    store_mesh(isolated_mesh_state)
    stored = slice_stl(stl, output=tmp_path / "b.gcode")

    assert stored.levelling == "stored"
    assert (stored.layer_count, stored.filament_g, stored.print_time_seconds) == (
        probed.layer_count,
        probed.filament_g,
        probed.print_time_seconds,
    )
    assert "stored mesh" in stored.summary()
